#! /usr/bin/env python
# encoding: utf-8

import sys, os
import Utils, Options

def configure(conf):
	conf.check_cfg(package='gtkmm-2.4', atleast_version='2.4', uselib_store='GTKMM')
	conf.check_cfg(package='libglademm-2.4', atleast_version='2.4', uselib_store='GLADEMM')
	#conf.check_tool('boost')
	conf.env['CXXFLAGS'] = '-I/usr/local/include'
	return
	
def build(bld):
	obj = bld.new_task_gen('cxx', 'staticlib')
	obj.target = 'netwars'
	#obj.uselib = 'BOOST'
	obj.includes = '.. ../lib'
	obj.defines = 'TIXML_USE_TICPP=1 TIXML_USE_STL=1'
	obj.find_sources_in_dirs('. game_mechanics map_loader units')
	return

