#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

import sys, os
import Utils, Options

def configure(conf):
	return
	
def build(bld):
	obj = bld.new_task_gen('cxx', 'staticlib')
	obj.target = 'tinyxml'
	obj.defines = 'TIXML_USE_STL=1 TIXML_USE_TICPP=1'
	obj.find_sources_in_dirs('tinyxml')
	obj.install_path = '../src'
	
	json = bld.new_task_gen('cxx', 'staticlib')
	json.target = 'json'
	json.defines = ''
	json.find_sources_in_dirs('json')
	json.install_path = '../src'
	
