#! /usr/bin/env python
# encoding: utf-8

from logging import fatal, error
import sys, os
import Utils, Options, Configure

def set_options(opt):
	pass

def configure(conf):
	pass
					
def build(bld):
	gui = bld.new_task_gen('cxx', 'program')
	gui.target = 'netwars'
	gui.uselib = 'BOOST_FILESYSTEM BOOST_SIGNALS BOOST_SYSTEM GTKMM CAIROMM GLADEMM'
	gui.uselib_local = 'netwars tinyxml'
	gui.includes = '. .. ../lib'
	gui.defines = 'TIXML_USE_TICPP=1 TIXML_USE_STL=1 GUI_GTK=1'
	gui.find_sources_in_dirs('.')
	gui.install_path = '..'

