######################################################################
# Automatically generated by qmake (2.01a) Do Feb 12 16:23:37 2009
######################################################################

TEMPLATE = app
TARGET = netwars
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h MapWidget.h
FORMS += mainWindow.ui
SOURCES += main.cpp MainWindow.cpp MapWidget.cpp
RESOURCES += data.qrc
