#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

import sys, os
import Utils, Options

def configure(conf):
	#conf.check_cfg(package='gtkmm-2.4', atleast_version='2.4', uselib_store='GTKMM')
	#conf.check_cfg(package='libglademm-2.4', atleast_version='2.4', uselib_store='GLADEMM')
	pkgconf = conf.create_pkgconfig_configurator()
	
	conf.env['CXXFLAGS'] = '-IC:\MinGW\local\include'
	return
	
def build(bld):
	obj = bld.new_task_gen('cxx', 'program')
	obj.target = 'netwars'
	obj.uselib = 'GTKMM GLADEMM'
	obj.defines = 'TIXML_USE_STL=1 TIXML_USE_TICPP=1'

	obj.find_sources_in_dirs('. game_mechanics  graphics gui gui/gtk map_loader  tinyxml units')

