#! /usr/bin/env python
# encoding: utf-8

from logging import fatal, error
import sys, os
import Utils, Options, Configure

def set_options(opt):
	opt.tool_options('boost')
	opt.add_option('--gui', type='string', default='NO', help='Choose the GUI [NO|QT|COCOA]. Default is NO', dest='gui')
	opt.add_option('--debug', action='store_true', help='Debug build (-g) or release build (-O2)?', dest='debug')
	pass

def configure(conf):
	windows = sys.platform.startswith('win')
	conf.env['GUI'] = Options.options.gui
	conf.env['DEBUG'] = Options.options.debug

	#conf.env['BOOST'] = ' -lboost_filesystem -lboost_system -lboost_signals'

	conf.check_tool('boost')
	conf.check_boost(lib='signals filesystem system', kind='STATIC_BOTH')
	
	if conf.env['GUI'] == 'GTK':
		conf.check_cfg(atleast_pkgconfig_version='0.0.0')
		conf.check_cfg(package='gtkmm-2.4', args='--cflags --libs', uselib_store='GTKMM')
		conf.check_cfg(package='cairomm-1.0', args='--cflags --libs', uselib_store='CAIROMM')
		conf.check_cfg(package='libglademm-2.4', args='--cflags --libs', uselib_store='GLADEMM')

	if conf.env['DEBUG']:
		conf.env.append_value('CXXFLAGS', '-g')
		conf.env.append_value('LINKFLAGS', '-g')
		conf.env.append_value('CXXFLAGS', '-ggdb')
		conf.env.append_value('LINKFLAGS', '-ggdb')
	else:
		conf.env.append_value('CXXFLAGS', '-O2')
		conf.env.append_value('LINKFLAGS', '-O2')

	if windows:
		conf.env.append_value('CXXFLAGS', '-IC:\MinGW\local\include -Wall')
		conf.env.append_value('LINKFLAGS', '-LC:\MinGW\local\lib')
	else:
		conf.env.append_value('CXXFLAGS', '-I/usr/local/include -Wall')
		
	conf.sub_config('lib')
	
	if conf.env['GUI'] == 'GTK':
		conf.sub_config('gui_gtk')

def build(bld):
	bld.add_subdirs('lib')

	netwars = bld.new_task_gen('cxx', 'staticlib')
	netwars.target = 'netwars'
	netwars.uselib = 'BOOST_FILESYSTEM BOOST_SIGNALS BOOST_SYSTEM BOOST'
	netwars.uselib_local = 'tinyxml'
	netwars.includes = '. lib'
	netwars.defines = 'TIXML_USE_TICPP=1 TIXML_USE_STL=1'
	netwars.find_sources_in_dirs('game game/game_mechanics game/map_loader game/units game/gui')
	netwars.install_path = '../src'

